### PR TITLE
SublimeText 3 support (continued work started by @hsaid)

### PR DESCRIPTION
**Pull request by waj**
I continued the PR made by @hsaid. Right now I'm able to compile and use autocomplete.

### CODE REVIEW

**Comment by artempartos** [comment]
up!

**Comment by tuscland** [comment]
up!

**Comment by marco-m** [comment]
up!

**Comment by pokidovea** [comment]
up!

**Comment by marco-m** [comment]
hello? Is this project still alive / interested in ST3 ?

**Comment by ostinelli** [comment]
@marco-m, not currently doing any work on it.

**Pull request closed without merging**
