### PR TITLE
Added Windows support

### PR DESCRIPTION
**Pull request by vleushin**
Please review and see if it breaks stuff in OSX/Linux. Meanwhile, I will look into remaining WIndows hacks and figure out how to avoid them.

### CODE REVIEW

**Comment by ostinelli** [comment]
Hello @vleushin,

thank you for this contribution. If you feel there still are hacks, shouldn't we wait until you are done fixing those? What hacks are you referring to?

**Comment by vleushin** [comment]
Yep, sure, no rush.

Hacks I'm referring to:

``` python
if sublime.platform() == 'windows':
    current_env = {} # <-- hack

def shellquote(self, s):
    if s: # <-- hack

def set_app_name(self):
    if self.project_root: # <-- hack
        # and I had to use project_root instead of test_root
```

**Comment by ostinelli** [comment]
> and I had to use project_root instead of test_root

can you please expand on that? does this work with large project that have apps released in the `/apps` directory, with individual `rebar.config` files and such?

**Comment by vleushin** [comment]
Not sure. Before we go forward I think we need to agree on some projects (with different setups) I should test against.

**Comment by vleushin** [comment]
I checked out mochiweb project (https://github.com/mochi/mochiweb) and I was getting errors because of test_root. I will get back on this on weekend.

**Comment by Andy-Richards** [comment]
Hi, running any of the mappings in Default (Windows).sublime-keymap results in the error ...

WindowsError: [Error 3] The system cannot find the path specified: u'C:\some_path\some_project\src\_._'

I have a rebar.config which specifies my app dirs in the {sub_dirs,[]} tuple. So for me the paths should be similar to...

u'C:\some_path\some_project\apps\some_app\src\_._'
u'C:\some_path\some_project\apps\some_other_app\src\_._'

I'll try and see if I can see where this occurring or if my rebar.config isn't being found.

Andy.

**Comment by ostinelli** [comment]
Any news regarding this pull request and issue #40? Things have changed a lot since this version, and cannot be merged.

**Comment by vleushin** [comment]
I will take a look into it.

**Comment by ostinelli** [comment]
Ok closing this, feel free to re-open once done.

**Pull request closed without merging**
