### PR TITLE
Better project directory and source file tests

### PR DESCRIPTION
**Pull request by jwheare**
The current tests fail if a user stores _all_ their source code in a ~/src directory

core: Test for ebin directory because it's required by the rebar layout, and is more erlang specific than src.

support/libparser: Exclusion test for .eunit instead of inclusion in src. Not sure if there are other .erl files we'd want to ignore.

### CODE REVIEW

**Comment by ostinelli** [comment]
Isn't `src` required by all best practices?

**Comment by jwheare** [comment]
The point is that if there's a non-erlang src directory _above_ the project dir then the test fails, so it can't be used as a foolproof way of identifying an erlang project.

**Comment by ostinelli** [comment]
I see. Will get into this asap. Thank you.

**Comment by ostinelli** [comment]
merged, thank you 27dc992f166050ba81ddadaa103077537b2b54b5

**Pull request closed without merging**
